name: 检查表格是否正确

on:
    workflow_dispatch:
    push:
      branches:
        - main
        - Account
      paths:
        - 'Search-table.md'
    pull_request:
      paths:
        - 'Search-table.md'

jobs:
  check-table:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置 Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: 运行检查
      id: table-check
      run: |
        node .action_scripts/table-checker.js
        echo "result=$?" >> $GITHUB_ENV

    - name: 设置标签
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const result = parseInt(process.env.result);
          const labelsToAdd = [];

          if (result === 0) {
            labelsToAdd.push('检查：通过');
          } else if (result === 1 || result === 3) {
            labelsToAdd.push('检查：异常');
          }
          if (result === 2) {
            labelsToAdd.push('检查：重复');
          }
          if (result === 1 || result === 2 || result === 3) {
            labelsToAdd.push('需要提交者确认');
          }

          if (labelsToAdd.length > 0) {
            const { context } = require('@actions/github');
            const { repo, pull_request } = context.issue;

            const octokit = require('@actions/github').getOctokit(process.env.GITHUB_TOKEN);

            await octokit.issues.addLabels({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: pull_request.number,
              labels: labelsToAdd
            });
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
